apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: front
build:
  artifacts:
  - image: front
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml
