apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: service
          image: front:latest
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: docker
            - name: DB_URL
              value: postgres.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: AUTH_URL
              value: auth.default.svc.cluster.local
            - name: REDIS_URL
              value: redis.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8080
